"""Regression checks for the optional wall-display template."""

from pathlib import Path

import yaml

TEMPLATE_PATH = Path("dashboard_templates/wall_display_card.yaml")


def test_wall_display_template_is_valid_yaml() -> None:
    """The copyable dashboard template remains valid YAML."""
    template = yaml.safe_load(TEMPLATE_PATH.read_text(encoding="utf-8"))

    assert template["type"] == "vertical-stack"
    assert isinstance(template["cards"], list)


def test_wall_display_uses_real_counter_entity_ids() -> None:
    """Example counter IDs match the entity names generated by Home Assistant."""
    template = TEMPLATE_PATH.read_text(encoding="utf-8")

    assert "_ruckmeldungen_positive" in template
    assert "_ruckmeldungen_negative" in template
    assert "_ruckmeldungen_positiv\n" not in template
    assert "_ruckmeldungen_negativ\n" not in template


def test_wall_display_countdown_is_large_orange_and_state_safe() -> None:
    """Only a numeric active countdown receives the emphasized presentation."""
    template = TEMPLATE_PATH.read_text(encoding="utf-8")

    assert "Number.isFinite(Number(raw))" in template
    assert "return 'Unbekannt';" in template
    assert "var(--warning-color, #ff9800)" in template
    assert "return active ? '34px'" in template
    assert "_ruckmeldefrist_countdown_2" not in template
